version: 2
updates:
  - package-ecosystem: docker
    directory: /.ci
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /src/otx/api/usecases/exportable_code/demo
    schedule:
      interval: daily
